name: Front-End CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Fix permissions
        run: npm rebuild

      - name: Gerar build
        run: npm run build