name: Front-End CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          - name: Instalar dependências
        run: npm ci

      # ADICIONE ESTE PASSO AQUI EMBAIXO:
      - name: Dar permissão de execução ao Vite
        run: chmod +x ./node_modules/.bin/vite

      - name: Gerar construir
        run: npm run build

      - name: Install dependencies
        run: npm ci
